(define (problem p0)
    (:domain painting)
  (:objects block sprayer red blue green)
  (:init (color-of block red)
         (color-of sprayer green)
         (on-table block)
         (on-table sprayer)
         (clear block)
         (clear sprayer)
         (is-obj sprayer)
         (is-obj block)
         (is-sprayer sprayer)
         (is-block block)
         (is-color red)
         (is-color blue)
         (is-color green)
         (arm-empty))
  (:goal (and (color-of block green) (arm-empty))))
