(define (problem p0)
    (:domain painting)
  (:objects A B sprayer red blue green)
  (:init (color-of A red)
         (color-of B red)
         (color-of sprayer green)
         (on A B)
         (on-table B)
         (on-table sprayer)
         (clear A)
         (clear sprayer)
         (is-obj A)
         (is-obj B)
         (is-obj sprayer)
         (is-block A)
         (is-block B)
         (is-sprayer sprayer)
         (is-color red)
         (is-color blue)
         (is-color green)
         (arm-empty))
  (:goal (and (color-of A green) (on A B) (arm-empty))))
